### ISSUE TITLE
script event onload not working when is type module

### ISSUE THREAD

**Issue by eduardocque** [jsdom/jsdom#3519] opened 2023-03-16 00:52 UTC
### Basic info:

- **Node.js version: 18
- **jsdom version: 21.1.1

Happens in any scenario where you try to load a script dynamically as module, when is `text/javascript` works fine, but module no

in chrome after the script is loaded i can get perfectly the event

```js
const script = this.jsDom.window.document.createElement('script');
script.src = url;
script.type = 'module';
script.async = true;

script.onload = async () => {
 await fancyCode();
  console.log('hi')
};

 this.jsDom.window.document.head.appendChild(script);
```

**Comment by domenic** [comment] 2023-03-16 01:04
Dupe of #2475.

**Closed by domenic** 2023-03-16 01:04 UTC

**Comment by eduardocque** [comment] 2023-03-16 01:21
oh sorry, thx for the reference
