### ISSUE TITLE
Element.innerText is undefined

### ISSUE THREAD

**Issue by MakingStuffs** [jsdom/jsdom#3335] opened 2022-02-05 09:09 UTC
### Basic info:

- **Node.js version:** ^14
- **jsdom version:** ^19.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const { window: { document } }  = new JSDOM(`<body>Hello</body>`);

console.log(document.body.innerText); // undefined
console.log(document.body.textContent); // Hello

```
### How does similar code behave in browsers?

In a normal browser the above code would log the same as the `textContent` method -- Hello

**Comment by domenic** [comment] 2022-02-05 19:46
Dupe of https://github.com/jsdom/jsdom/issues/1245

**Closed by domenic** 2022-02-05 19:46 UTC
