### ISSUE TITLE
innerText undefined in jsdom but defined in chrome?

### ISSUE THREAD

**Issue by gc** [jsdom/jsdom#2670] opened 2019-09-21 07:35 UTC
### Basic info:

- **Node.js version:** 10.14.2
- **jsdom version:** 15.1.1

### Minimal reproduction case

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

JSDOM.fromURL(`http://services.runescape.com/m=poll/oldschool/results.ws?id=704`).then(dom => {
console.log(dom.window.document.querySelector(".widescrollWrapper b").textContent); // Total Number of Votes: 16869
console.log(dom.window.document.querySelector(".widescrollWrapper b").innerText); // undefined
});
```
### How does similar code behave in browsers?

On that page in chrome, this gives `true` in the console, indicating that innerText isnt undefined:
```js
document.querySelector(".widescrollWrapper b").textContent === document.querySelector(".widescrollWrapper b").innerText // true
```

This seems like a bug as it behaves differently from chrome/browsers.

**Comment by domenic** [comment] 2019-09-21 07:39
Dupe of #1245

**Closed by domenic** 2019-09-21 07:39 UTC
