### ISSUE TITLE
ClipboardEvent not available in window

### ISSUE THREAD

**Issue by wtho** [jsdom/jsdom#2912] opened 2020-03-22 22:14 UTC
### Basic info:

- **Node.js version:** v13.11.0
- **jsdom version:** v16.2.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const { window } = new JSDOM(``);
window.ClipboardEvent; // undefined
```

### How does similar code behave in browsers?
In Chrome v80:
`window.ClipboardEvent // ClipboardEvent() { [native code] }`

### MDN Documentation
https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent

**Comment by catalin-luntraru** [comment] 2020-05-01 10:22
Here's a mock for the clipboard event. You use the regular `Event` and manually set the `clipboardData` property

```javascript
const event = new Event('paste', { bubbles: true, cancelable: true })
event.clipboardData = {
  getData () { return 'copied text' }
}
document.dispatchEvent(event)
```

**Comment by nickmccurdy** [comment] 2020-12-22 06:51
Duplicate of #1568

**Closed** 2020-12-22 18:13 UTC
Labels: feature
