### ISSUE TITLE
I'm a beginner, but I think it's a mistake...

### ISSUE THREAD

**Issue by beria23** [jsdom/jsdom#3409] opened 2022-07-27 08:57 UTC
I was writing my first parser and immediately encountered a problem... Although maybe I'm an idiot.

import jsdom from "jsdom";
const { JSDOM } = jsdom;
const dom = new JSDOM(`<html>
<head></head>
<body>
  <script  type="module">
    import { render } from 'https://cdn.skypack.dev/million';
    render(document.body, 'You won $$$!');
  </script>
</body>
</html>
`, { runScripts: "dangerously" });

console.log(dom.window.document.body.innerHTML);

**Actual result:**
<script type="module">
    import { render } from 'https://cdn.skypack.dev/million';
    render(document.body, 'You won $$$!');
  </script>
**What I've been waiting for**
   You won $$$!

ps: english is not my native language

**Comment by vilbergs** [comment] 2022-08-02 08:45
You should look into 19136463

**Comment by vilbergs** [comment] 2022-08-02 08:48
ES module scripts are deferred by default, so your code will not have executed by the time your program logs out tho the terminal.

I'm no JSDOM expert, but you could look into https://github.com/jsdom/jsdom#asynchronous-script-loading

**Comment by domenic** [comment] 2022-10-01 10:49
Dupe of #2475.

**Closed by domenic** 2022-10-01 10:49 UTC
