### ISSUE TITLE
Please add window.crypto in JSDOM

### ISSUE THREAD

**Issue by anant-k-singh** [jsdom/jsdom#2934] opened 2020-04-05 07:18 UTC
### Basic info:

- **Node.js version:** v10.16.3
- **jsdom version:** v16.2.1

### How does similar code behave in browsers?

window.crypto.getRandomValues( ) exists in browser.

**Comment by TimothyGu** [comment] 2020-04-05 13:33
Duplicate of #1612.

**Closed by TimothyGu** 2020-04-05 13:33 UTC
