### ISSUE TITLE
Replace request-promise-native

### ISSUE THREAD

**Issue by guimard** [jsdom/jsdom#3030] opened 2020-08-24 09:48 UTC
### Basic info:

- **Node.js version:** 12
- **jsdom version:** last

### Resume :

According to [upstream warning](https://github.com/request/request-promise-native#deprecated), request-promise-native is deprecated and should be replaced. It is used in

https://github.com/jsdom/jsdom/blob/5279cfda5fe4d52f04b2eb6a801c98d81f9b55da/lib/jsdom/browser/resources/resource-loader.js#L4-L6

**Comment by SimenB** [comment] 2020-09-18 06:35
Duplicate of #2792

**Comment by zynyz** [comment] 2020-10-21 00:33
Hi guys --

This has now become a breaking issue for me. My Google cloud function will no longer deploy. The build process is treating the deprecation warning as a fatal error. This seems to be new behavior since yesterday:

```
Build failed: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142 
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142 
npm WARN deprecated har-validator@5.1.5: this library is no longer supported 
npm ERR! Cannot read property 'failed' of undefined 
npm ERR! A complete log of this run can be found in: 
npm ERR! /builder/home/.npm/_logs/2020-10-20T23_16_10_668Z-debug.log; Error ID: 49341d49
```

* I apologize for any bad formatting. The preview pane does not seem to want to display today.

**Closed** 2021-03-07 19:28 UTC
