### ISSUE TITLE
Proper way to work with jQuery across-files?

### ISSUE THREAD

**Issue by CoryGH** [jsdom/jsdom#3083] opened 2020-12-18 01:48 UTC
### Basic info:

- **Node.js version:** latest
- **jsdom version:** latest

### Minimal reproduction case
MyClass.test.js:
```js
const $ = require("jquery");
const { JSDOM } = require("jsdom");
const MyClass = require("./MyClass.js");

describe('MyClass', () => {
    it('should allow creation', () => {
        expect(() => {
            const dom = new JSDOM(`<!DOCTYPE html><div id="divMain"></div>`);
            const window = $(dom.window);
            let parent = $("#divMain", window);
            if (parent.length < 1) { throw 'Not found!'; }
            let myClass = new MyClass({
                Parent: parent
            });
        }).not.toThrow();
    });
});
```

MyClass.js:
```js
const $ = require("jquery");

function MyClass(settings) {
    this._parent = settings.Parent;
    this._parent.append('<div class="myclass"></div>');
    this._container = $(".myclass", this._parent).last();
    if (this._container.length < 1) { throw 'Not found!'; }
}
MyClass.prototype.constructor = MyClass;

module.exports = MyClass;
```

The above would be my ideal with the test executed via jest,) however this actually fails before ever making it to the MyClass initialization on the line `let parent = $("#divMain", window);` with the div never being selected.  Is there something basic I'm missing here?  I've seen a bunch of older examples with how this was apparently done in the past, but none appear to map to the current codebase of both jsdom and jquery.

**Comment by Pustur** [comment] 2020-12-18 04:12
I cannot reproduce the issue. I made a new project, installed `jest`, `jsdom`, `jquery` and copy-pasted your code. When I run the test is gives me an error at this line:

```js
this._parent.append("<div class="myclass"></div>");
```

Because you used the same quotes for the string and when defining `myclass`, but if I fix that problem then the test passes.

Can you share the error message?

**Comment by CoryGH** [comment] 2020-12-18 04:53
@Pustur apologies for the typo, I wrote it in the post textbox while simplifying the giant piece of code I have.  If you can inspect the statement `let parent = $("#divMain", window);` you'll see that `parent` never actually gets set.  In my actual test this blows up down the road while trying to read properties off of objects.  I'll modify the example in the original post to demonstrate this and correct the typo.

**Comment by Pustur** [comment] 2020-12-18 05:00
Ok I can see the problem now, sorry but I don't know what's going on.
Hopefully someone else will be able to help you.

**Comment by oshawa-connection** [comment] 2021-02-09 10:24
[Check out this example.](https://jestjs.io/docs/en/tutorial-jquery)  Does that help?

**Comment by domenic** [comment] 2021-03-07 19:31
This seems to be a Jest question, not a jsdom question, so I'll close this.

**Closed by domenic** 2021-03-07 19:31 UTC
