### ISSUE TITLE
Use ElementImpl.prototype.setAttribute/getAttribute inside of HTML properties

### ISSUE THREAD

**Issue by davidturissini** [jsdom/jsdom#2158] opened 2018-02-24 01:07 UTC
### Basic info:

JSDOM HTML property setters/getters internally call `this.setAttribute` and `this.getAttribute`, respectively.

This is different from browser behavior, which do not call `setAttribute` and `getAttribute` directly on the Element itself. I think JSDOM can preserve this by calling `getAttribute` and `setAttribute` on `ElementImpl.prototype` directly.

For an example of there this happens in JSDOM, please see https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLElement-impl.js#L78

For example of browser behavior, see below.

- **Node.js version:** 8.7.0
- **jsdom version:** 11.6.2

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');
const dom = new JSDOM('');
var div = dom.window.document.createElement('div');
div.setAttribute = function () {
  console.log('I should not be called')
}

var descSet = Object.getOwnPropertyDescriptor(dom.window.HTMLElement.prototype, 'title').set;

descSet.call(div, 'new title');
```

### How does similar code behave in browsers?

http://jsbin.com/koyilegopa/edit?html,js,console,output

**Comment by TimothyGu** [comment] 2018-02-24 01:12
> JSDOM HTML property setters/getters internally call `this.setAttribute` and `this.getAttribute`, respectively.

When you see `getAttribute` or `setAttribute` in the code, it should always refers to the impl version of the function, since `this` is an instance of `HTMLElementImpl` rather than `HTMLElement`, and thus `ElementImpl` rather than `Element`.

Can you replace `console.log('I should not be called')` with `console.trace()` and post the result here?

**Comment by davidturissini** [comment] 2018-02-24 01:16
@TimothyGu Yes, I understand that `getAttribute` and `setAttribute` resolve to HTMLElementImpl.prototype, but what I am suggesting is that the setters call this method directly, via:
```HTMLElementImpl.prototype.setAttribute.call(this, value)``` rather than through `this.setAttribute(value)`

My use case is monkey patching `setAttribute` and `getAttribute`, and elsewhere in my code calling the property setter directly. This works fine in browsers but not in our testing environments.


```
Trace
    at HTMLDivElement.div.setAttribute (/Users/dturissini/Development/raptor/packages/lwc-engine/jsdom.js:5:11)
    at HTMLDivElement.set [as title] (/Users/dturissini/Development/raptor/node_modules/jsdom/lib/jsdom/living/generated/HTMLElement.js:69:10)
    at Object.<anonymous> (/Users/dturissini/Development/raptor/packages/lwc-engine/jsdom.js:10:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```

**Comment by pmdartus** [comment] 2019-10-13 07:52
This issue is still reproducible today on the latest version of master. Because of the changes made in 4d75714e684750f5c4638e2f69525235f9ed4468, the original code repro needs to be updated (replacing `setAttribute` with `setAttributeNS`). 

```js
const { JSDOM } = require('jsdom');
const dom = new JSDOM('');
var div = dom.window.document.createElement('div');
div.setAttributeNS = function () {
  console.log('I should not be called')
}

var descSet = Object.getOwnPropertyDescriptor(dom.window.HTMLElement.prototype, 'title').set;

descSet.call(div, 'new title'); // log: I should not be called
```

This issue should be fixed at the webidl2js level. Instead of invoking the wrapper class methods for reflected attributes, it should invoke the impl methods.

**Closed** 2019-10-14 13:24 UTC
