### ISSUE TITLE
Fetch is not defined

### ISSUE THREAD

**Issue by kartmax-product-team** [jsdom/jsdom#3413] opened 2022-08-02 06:14 UTC
I am trying to parse the HTML containing scripts, dom manipulation, and fetch calls. but when I try to HTML it shows ` Error: Uncaught [ReferenceError: fetch is not defined]`

_**HTML mockup that I need to parse with HTML**_

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Website</title>
    <link rel="stylesheet" href="./style.css">
    <link rel="icon" href="./favicon.ico" type="image/x-icon">
  </head>
  <body>
    <main
      <div id="placeHolder"></div>
    </main>
	<script>
    	document.getElementById("placeHolder").innerHTML = "test"
      fetch(
      "https://engine.kartmax.in/api/web/default-header/5d919085085141e48af5ed7fc78e58c4"
    );
    </script>
  </body>
</html>
```

**Comment by domenic** [comment] 2022-10-01 09:04
Dupe of https://github.com/jsdom/jsdom/issues/1724 and does not follow the issue template.

**Closed by domenic** 2022-10-01 09:04 UTC
