### ISSUE TITLE
ReferenceError: MessageChannel is not defined

### ISSUE THREAD

**Issue by dominuslabs** [jsdom/jsdom#2984] opened 2020-05-30 03:33 UTC
### Basic info:

- **Node.js version:** v12.16.1
- **jsdom version:** 16.2.2

### Minimal reproduction case

```js
const axios = require("axios");
const { JSDOM } = jsdom;
const channels = require('worker_threads');

async function main() {
    r = await axios.get("https://patrickhlauke.github.io/recaptcha/");
    if (r.error) {
        console.log("Eror occured - ",r.error)
    } else {
        const dom = new JSDOM(r.data,{
            url: "https://patrickhlauke.github.io/recaptcha/",
            contentType: "text/html",
            includeNodeLocations: true,
            runScripts: "dangerously",
            pretendToBeVisual: true,
            resources: "usable",
            beforeParse(window) {
                window.MessageChannel = channels.MessageChannel;
            }
        });
        console.log(dom.window.document);
    }
}

// Expected -> 'dom.window.document result'
// Actual ---> '(node:68114) UnhandledPromiseRejectionWarning: ReferenceError: MessageChannel is not defined'
```

### How does similar code behave in browsers?
The result from dom.window.document (I didn't add a link to anything here since I assume everyone reading this knows, to some degree, the result of the above code.

**Comment by domenic** [comment] 2020-07-10 01:05
Dupe of https://github.com/jsdom/jsdom/issues/2448

**Closed by domenic** 2020-07-10 01:05 UTC
