### ISSUE TITLE
External CSS - missing objects

### ISSUE THREAD

**Issue by termitek12** [jsdom/jsdom#2650] opened 2019-08-20 15:45 UTC
`var ss = document.styleSheets;`

However ss is missing some fields.. like **href** or **ownerNode** or **cssSelector** (I tested this with **chrome** and **ff** and there always is for example **href** in browser dev tools). Why is that? Will this be fixed?

**Comment by Exagone313** [comment] 2020-04-22 09:20
Duplicate of #992

**Closed** 2020-04-22 13:35 UTC
Labels: css, feature
