### ISSUE TITLE
Found GNU Licensed File in this project

### ISSUE THREAD

**Issue by inventivejon** [jsdom/jsdom#3220] opened 2021-07-12 11:45 UTC
Hi, 

Given the comment in the file .\lib\jsdom\browser\default-stylesheet.js, which reads 

....
This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 ....

, the respective file is licensed as GPLv2 or later. On the other hand, the overall project is licensed as MIT. Wouldn't the template imply, that the overall project must be licensed as GPLv2? Or is the copyright template in the file misplaced / an old artifact?

**Comment by domenic** [comment] 2021-07-12 16:21
Dupe of https://github.com/jsdom/jsdom/issues/2642

**Closed by domenic** 2021-07-12 16:21 UTC
