### ISSUE TITLE
`nodeLocation` returns undefined even though `includeNodeLocations` is `true`

### ISSUE THREAD

**Issue by tscpp** [jsdom/jsdom#2988] opened 2020-06-09 15:01 UTC
### Basic info:

- **Node.js version:** 14.3.0
- **jsdom version:** 16.2.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  includeNodeLocations: true
};
const dom = new JSDOM(`
<span id ="test">test</span>
`, options);

...
if (dom.nodeLocation(dom.window.document.getElementById('test')) === undefined)
  throw new Error('Why is ElementLocation undefined?')
...
```

### How does similar code behave in browsers?

uuhh... __¯\\_(ツ)_/¯__

**Comment by tscpp** [comment] 2020-06-09 15:05
I noticed that `dom.serialize()` returns `<html><head></head><body><span>test</span></body></html>` when I send in `<span>test</span>` as html, which is correct, but nodeLocation is undefined. When I send in `<html><head></head><body><span>test</span></body></html>` as html nodeLocation works.

**Comment by tscpp** [comment] 2020-06-09 15:06
A temporary fix can be to send in `<span>test</span>` as HTML and then send in the serialized html to another `new JSDOM`.

**Comment by domenic** [comment] 2020-07-11 18:08
I cannot reproduce this locally using Node v14.3.0 and jsdom v16.3.0 (which should have no changes since 16.2.1):

```js
const { JSDOM } = require(".");

const options = {
  includeNodeLocations: true
};
const dom = new JSDOM(`
<span id ="test">test</span>
`, options);

console.log(dom.nodeLocation(dom.window.document.getElementById('test')));
```

logs

```
$ node test.js
{
  startLine: 2,
  startCol: 1,
  startOffset: 1,
  endLine: 2,
  endCol: 29,
  endOffset: 29,
  attrs: [Object: null prototype] {
    id: {
      startLine: 2,
      startCol: 7,
      startOffset: 7,
      endLine: 2,
      endCol: 17,
      endOffset: 17
    }
  },
  startTag: {
    startLine: 2,
    startCol: 1,
    startOffset: 1,
    endLine: 2,
    endCol: 18,
    endOffset: 18,
    attrs: [Object: null prototype] { id: [Object] }
  },
  endTag: {
    startLine: 2,
    startCol: 22,
    startOffset: 22,
    endLine: 2,
    endCol: 29,
    endOffset: 29
  }
}
```

The same occurs in RunKit: https://runkit.com/domenicdenicola/5f0a00083a8e3c001acc80c9

I'll close this, but let us know if you have another reproduction case; preferably, supply a RunKit link.

**Closed by domenic** 2020-07-11 18:08 UTC
