### ISSUE TITLE
fromURL returns promise before window.onload inside html script has fired.

### ISSUE THREAD

**Issue by miggs125** [jsdom/jsdom#2557] opened 2019-04-17 15:04 UTC
### Basic info:
- **Node.js version:**  10.15.0
- **jsdom version:**  13.2.0 

When trying to use window.onload inside \<script\> tags within the \<head\> tags of the html code, JSDOM's fromURL method resolves the promise before window.onload has had a chance to finish firing.

### Minimal reproduction case

```js
const { JSDOM, ResourceLoader } = require('jsdom');

const resourceLoader = new ResourceLoader({
  proxy: "",
  strictSSL: true,
});


function foo() {
  
 JSDOM.fromURL('http://127.0.0.1:3000/', {
    resources: resourceLoader,
    runScripts: 'dangerously',
    beforeParse(window) {
      window.confirm = (message) => {
        console.log(`this is the message: '${message}'`);
        return false;
      }
    }
  }).then((dom) => {
    console.log('THIS SHOULD EXECUTE LAST')
    console.log(dom.window.document.getElementById("test").innerHTML);
  });

}


foo();
```
HTML fetched from '127.0.1:3000/':
```js
<!doctype <!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script>
        window.onload = () => {
            console.log('ONLOAD SHOULD EXECUTE THIRD');
            let element = document.body.querySelector("#test")
            if (window.confirm("Click OK or CANCEL")) {
                element.innerHTML = 'OK CLICKED';
            } else {
                element.innerHTML = 'CANCEL CLICKED';
            }
            document.body.appendChild(element);
        }
            console.log('THIS SHOULD EXECUTE FIRST');
    </script>
</head>

<body>
    <h2 id="header">Window Onload Test</h2>
    <p id="test"></p>
    <script>
        console.log('THIS SHOULD EXECUTE SECOND');
    </script>
</body>
</html>
```

Expected output: 
```
THIS SHOULD EXECUTE FIRST
THIS SHOULD EXECUTE SECOND
ONLOAD SHOULD EXECUTE THIRD
this is the message: 'Click OK or CANCEL'
CANCEL CLICKED
```

Actual output:
```
THIS SHOULD EXECUTE FIRST
THIS SHOULD EXECUTE SECOND
THIS SHOULD EXECUTE LAST

ONLOAD SHOULD EXECUTE THIRD
```
If however, you replace:

```
.then((dom) => {
    console.log(dom.window.document.getElementById("test").innerHTML); 
    console.log('THIS SHOULD EXECUTE LAST') 
  });
```

with:
```
.then((dom) => {
    setTimeout(()=>{
      console.log(dom.window.document.getElementById("test").innerHTML);  
      console.log('THIS SHOULD EXECUTE LAST')
    },5000);
  });
```
the expected output is observed, indicating that the script within window.onload is firing properly, however, the promise received from JSDOM.fromURL is not allowing enough time for window.onload to execute.

**Comment by domenic** [comment] 2019-04-17 16:09
Yep, this is working as expected. If you want to wait for the load event, you should add a load event listener. The fromURL promise is not related to the load event; it is just when the JSDOM instance is constructed.

Closing since this is not a bug, but happy to continue discussing in the closed thread; perhaps the docs need updating to make this clearer.

**Closed by domenic** 2019-04-17 16:09 UTC

**Comment by miggs125** [comment] 2019-04-17 18:00
Thanks for the speedy reply @domenic 
How would I go about adding an event listener for this? I would like the DOM that jsdom constructs to reflect the changes created by window.onload...

**Comment by miggs125** [comment] 2019-04-17 18:49
update: I changed the code to the following and it appears to work properly:
```js
function foo() {
  let theDom;
  JSDOM.fromURL('http://127.0.0.1:3000/', {
    resources: resourceLoader,
    runScripts: 'dangerously',
    beforeParse(window) {
      window.confirm = (message) => {
        console.log(`this is the message: '${message}'`);
        return false;
      }
    }
  }).then((dom) => {
    return new Promise((resolve) => {
      if (dom.window.onload !== null) {
        dom.window.addEventListener("load", () => {
          console.log('THIS SHOULD EXECUTE LAST');
          theDom = dom;
          resolve(theDom)
        });
      } else {
        theDom = dom;
        resolve(theDom)
      }
    });
  }).then((dom) => {
    console.log(dom.window.document.querySelector("#test").innerHTML);
  });
}
```
May not be the best solution. I am open to alternatives.

**Comment by domenic** [comment] 2019-04-17 19:01
I'm not sure why you have the `dom.window.onload` check, but indeed, using `dom.window.addEventListener("load", ...)` is what I would do.
