### ISSUE TITLE
client.abort is not a function

### ISSUE THREAD

**Issue by lingxuan630** [jsdom/jsdom#2139] opened 2018-02-01 06:23 UTC
- **jsdom version:** v11.6.2

When I use xmlHttpRequest, it throw "client.abort is not a function". It is bug! Client is a instance of eventEmitter, and we should use emit.

Here is the problem:
```
TypeError: client.abort is not a function
      
      at XMLHttpRequest.abort (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:376:20)
      at Object.abort (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:422:13)
      at RequestManager.close (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:131:21)
      at Window.close (node_modules/jsdom/lib/jsdom/browser/Window.js:465:29)
```

**Comment by domenic** [comment] 2018-02-01 16:31
Thanks, but this did not follow the issue template, including a minimal example (with no external libraries). I will close it. Please edit to follow the issue template and then we can reopen.

**Closed by domenic** 2018-02-01 16:31 UTC

**Comment by hbowden** [comment] 2018-11-20 19:59
Running the below code with jest will reproduce the bug.

```const axios = require('axios');

describe('My First Test', function() {
  it('Create User with user API', function() {
    axios.get('localhost:8080/users/create')
      .then(function (response) {
      // handle success
      console.log(response);
    })
    .catch(function (error) {
      // handle error
      console.log(error);
    })
    .then(function () {
      // always executed
    });
  });
});```

**Comment by domenic** [comment] 2018-11-20 21:00
It's important to give an example that does not depend on third-party libraries like Jest or Axios, but instead follows the issue template to show that it's truly a problem with jsdom.

**Comment by timothywisdom** [comment] 2019-07-12 18:44
I'm also seeing this error. I have a jest test that attempts to fetch some async data which I purposely reject and I get back this same error. It works if I resolve the async promise but not when I reject it. I'm using moxios (a mock for the axios package).

My simplified test:
```
it("returns nicely when server error happen", async () => {
	let serverData;
	try {
		serverData = await fetchDataViaMoxiosAndReject();
	} catch (err) {
		console.log("Error state happened", err)
		serverData = err
	}
	expect(serverData ).toBeDefined();
	console.log("Test complete");
});
```

Like the above users, I'm also seeing the error:
```
Test suite failed to run

    TypeError: client.abort is not a function

      at XMLHttpRequest.abort (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:379:16)
      at Object.abort (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:425:13)
      at RequestManager.close (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:133:21)
      at Window.close (node_modules/jsdom/lib/jsdom/browser/Window.js:513:29)
```

Googling has only lead me to here. Would love to hear if anyone has made progress on this.

**Comment by blgm** [comment] 2019-07-17 09:10
I also saw this error. On investigation it turned out that an HTTP request was being made in the test which had no fake backend to handle it. It seems that JSDOM failed with this error on shutdown if there were pending requests. Perhaps that's what's going on for other people too?

**Comment by LeaDelannay** [comment] 2019-09-18 13:50
Hi, I had this problem with the IntelliJ console. 
I think the problem comes from the fact that it is a windows console. It does not use the same environment variables.
So I use the Cygwin console, and it works correctly.

**Comment by prakashk-dev** [comment] 2022-08-24 06:34
I also had the same problem, and it turns out that some of the test files imported `HttpClientModule` instead of `HttpClientTestingModule`. Replacing `HttpClientModule` with `HttpClientTestingModule` solved my problem.

**Comment by yonah-cadre** [comment] 2023-07-11 19:51
Strangely enough, I was experiencing this issue in a jest test as well, but wasn't using HttpClientModule. I resolved it by making the test `async` 🤷‍♂️ Not sure how
