### ISSUE TITLE
`.innerText` data doesn't show in `.innerHTML` and `.outerHTML`

### ISSUE THREAD

**Issue by williamd5** [jsdom/jsdom#3313] opened 2021-12-26 17:13 UTC
### Basic info:

- **Node.js version:** 16.13.0
- **jsdom version:** 19.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const button = new JSDOM("<button></button>").window.document.body.firstChild;

button.innerText = "Hello world!";

console.log(button.innerText) //> 'Hello world!'
console.log(button.innerHTML) //> ''
console.log(button.outerHTML) //> '<button></button>'
```

### How does similar code behave in browsers?

https://jsbin.com/cecuxafoli/edit?js,console

**Comment by domenic** [comment] 2022-01-15 17:25
Dupe of #1245.

**Closed by domenic** 2022-01-15 17:25 UTC
