### ISSUE TITLE
document.querySelector with multiple nth-child or multiple nth-of-type does not return results

### ISSUE THREAD

**Issue by mtom55** [jsdom/jsdom#2262] opened 2018-06-09 07:14 UTC
### Basic info:

- **Node.js version:** 8.11.2
- **jsdom version:** 11.11.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM('<h1><div></div></h1>')
dom.window.document.querySelector('h1:nth-child(1) div:nth-child(1)')  
// Returns nothing when we expect a <div>
dom.window.document.querySelector('h1:nth-of-type(1) div:nth-of-type(1)')
// returns nothing when we expect a div
```

This is the same thing working in chrome, copy and paste into any console window
```js
doc = document.createElement('div')
doc.innerHTML = '<h1><div></div></h1>'
doc.querySelector('h1:nth-child(1) div:nth-child(1)')
doc.querySelector('h1:nth-of-type(1) div:nth-of-type(1)')
```

Note nth-of-type and nth-child WORKS if you only have one of them, as soon as you have two
it no longer returns any results.

**Comment by Zirro** [comment] 2018-06-09 11:46
I can't reproduce this with the provided test case. If I add `console.log()` around the statements, I get a `HTMLDivElement` both times.

@mtom55 On IRC you mentioned a separate issue with `not()` as well - if you believe you have a test case for it, we'd appreciate if you create another issue.

**Comment by papandreou** [comment] 2018-06-09 12:05
I can reproduce it with the provided test case, but only if I downgrade `nwsapi` to 2.0.0. Must have been fixed in 2.0.1.

The latest released jsdom (11.11.0) depends on nwsapi@^2.0.0, so that explains why some people have ended up with 2.0.0 if they last `npm install`ed a while ago.

@mtom55, try `npm update` in the project where you saw this error.

**Comment by Zirro** [comment] 2018-06-09 12:12
@papandreou Good catch, thanks! The next release will include https://github.com/jsdom/jsdom/pull/2251 which should take care of it.

**Comment by papandreou** [comment] 2018-06-09 13:11
@Zirro, cool! You might want to refresh those updates before merging, nwsapi 2.0.2 is out now :)

**Comment by Zirro** [comment] 2018-06-09 17:31
Done - after talking to @dperini, version 2.0.3 was released with a few more fixes.

**Comment by mtom55** [comment] 2018-06-10 06:01
**Confirmed as Working** 
... with 2.0.3 in both my simplified test case and the much more complicated nested real-world examples.  Thanks for the ridiculously fast turn-around.

In relation to the not pseudo-selector, I can also confirm that is working as well (The issue before maybe related to the fact that a charCode 160 non-breaking space instead of a charCode 32 space 
had somehow made it into the selector in my code.  After removing the 160 non-breaking space, seems to work fine.  I'm not sure of what whitespace tokens should be considered in the selector and whether a ticket needs to be opened for this as it's a pretty edge/niche issue. If it does need to be supported you can create the selector simply by doing something like "#someId" + String.fromCharCode(160) + "div".

**Comment by dperini** [comment] 2018-06-10 11:04
@mtom55
thank you for reporting, here follows the W3 specification about whitespace:

https://www.w3.org/TR/2018/CR-selectors-3-20180130/#whitespace

> White space may appear between a combinator and the simple selectors around it. Only the characters "space" (U+0020), "tab" (U+0009), "line feed" (U+000A), "carriage return" (U+000D), and "form feed" (U+000C) can occur in whitespace. Other space-like characters, such as "em-space" (U+2003) and "ideographic space" (U+3000), are never part of whitespace.

**Closed** 2018-06-12 18:15 UTC
Labels: selectors
