### ISSUE TITLE
Possible regression: click event on checkbox input not triggering change (angularjs)

### ISSUE THREAD

**Issue by fluffynuts** [jsdom/jsdom#3387] opened 2022-06-24 12:30 UTC
### Basic info:
A recent dependabot PR to update jsdom from 16.4.0 to 16.7.0 causes existing tests to fail, specifically ones where "click" MouseEvents are raised on a checkbox and the `ng-change` handler is not fired. Performing a version-by-version check, the issue seems to have arisin in 16.6.0 (see attached reproduction repository)

~Similar to https://github.com/jsdom/jsdom/issues/731, I can work around this by grabbing the element and calling `.click()` on it.~
I thought I could work around like this, but I must have had the older jsdom installed. This does _not_ work (see repro repo). 

Trying to repro with "vanilla" JS doesn't trigger the same issue, so this is probably something specific to how angular handles change
events. Whilst I can (and will) just work around the issue as outlined above, this may affect other people.

### Minimal reproduction case
https://github.com/fluffynuts/jsdom-angularjs-click-no-change

**Comment by tiborpilz** [comment] 2022-07-11 12:43
> Trying to repro with "vanilla" JS doesn't trigger the same issue, so this is probably something specific to how angular handles change

I have the same issue with vue tests, so if it's something specific, it is something specific in how both vue and angular handle change.

**Comment by benfrancis** [comment] 2022-09-27 14:17
I think I have the same issue with a vanilla JS integration test. Performing a `click()` on a checkbox doesn't change its value.

I note that in the [release notes for 16.5.2](https://github.com/jsdom/jsdom/releases/tag/16.5.2) it says "Fixed radio buttons and checkboxes to not fire input and change events when disconnected."

What does "disconnected" mean here?

**Comment by domenic** [comment] 2022-09-28 01:02
Yes, that's roughly what disconnected means.

Any vanilla JS tests would be helpful. We don't investigate bug reports that include code from other libraries such as Vue, Angular, Jest, etc.

**Comment by benfrancis** [comment] 2022-09-29 10:11
> Any vanilla JS tests would be helpful. We don't investigate bug reports that include code from other libraries such as Vue, Angular, Jest, etc.

Sorry I may have been misleading, they are jest integration tests.

I found that I could fix the test regression by adding the checkbox node to the DOM before dispatching the click event. Based on the release notes for 16.5.2 this leads me to believe that it's an intentional change in behaviour, although surprising that such a breaking change would not trigger a major new release number rather than just 16.5.1 -> 16.5.2.

I'm not sure whether this is the same issue affecting Vue and Angular.

**Comment by domenic** [comment] 2022-09-29 10:38
Yeah, that's just a bug fix, since in browsers you cannot call `click()` on checkboxes that are not in the DOM, so any code relying on that before was buggy.

**Comment by benfrancis** [comment] 2022-09-29 10:45
> Yeah, that's just a bug fix, since in browsers you cannot call click() on checkboxes that are not in the DOM, so any code relying on that before was buggy.

That is one way of looking at it :)

**Comment by domenic** [comment] 2022-10-01 10:53
I'll close this, since we have a probable cause and nobody has provided a reproduction following the issue template anyway.

**Closed by domenic** 2022-10-01 10:53 UTC
