### ISSUE TITLE
File instance does not have an arrayBuffer method

### ISSUE THREAD

**Issue by ehab-cl** [jsdom/jsdom#3206] opened 2021-06-15 10:10 UTC
### Basic info:

- **Node.js version:**  v15
- **jsdom version:**  v16

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const { window } = new JSDOM("<!DOCTYPE html>");

const jsDomfile = new window.File(["sd"], "sa.txt");

console.log(jsDomfile.arrayBuffer()); // throws jsDomfile.arrayBuffer is not a function

```

### How does similar code behave in browsers?

Same issue here https://codesandbox.io/s/jsdom-testing-forked-894vb?file=/src/index.js:0-253 we can see in comparison that the native File has the arrayBuffer method.

**Comment by TimothyGu** [comment] 2021-06-16 06:19
Duplicate of #2555.

**Closed by TimothyGu** 2021-06-16 06:19 UTC

**Comment by jimmywarting** [comment] 2022-01-14 18:22
should pull the source from https://github.com/node-fetch/fetch-blob/blob/main/index.js
(more up to spec)
