### ISSUE TITLE
Unstable tests with jsdom v23.2.0

### ISSUE THREAD

**Issue by roman-gula** [jsdom/jsdom#3660] opened 2024-01-08 17:49 UTC
### Basic info:

- **Node.js version:** 20.10
- **jsdom version:** 23.2.0

I use **Vitest** with **jsdom** on my project and test are run very fast and stable. But after update jsdom to 23.2.0 tests started faling randomly. But when run one single test it is passed.

So for now I stopped on v23.1.0 which works fine.

**Comment by domenic** [comment] 2024-01-14 04:08
This seems likely a dupe of https://github.com/jsdom/jsdom/issues/3659, although you didn't specify how the tests were failing. For now, I'll close it assuming that's the case, but if you have more information, we can reopen.

**Closed by domenic** 2024-01-14 04:08 UTC
