### ISSUE TITLE
Add Support for ESM in script tags (type="module")

### ISSUE THREAD

**Issue by ivanjeremic** [jsdom/jsdom#3367] opened 2022-05-09 04:57 UTC
Add Support for ESM `<script type="module">...</script>`

```js
<script type="module">
 import func from "./logFunc.js";

 func();
</script>
```
I want to parse the needed JS and output it above the func(), this is something JSDom should do since All major browsers support this for a longer time now.

**Comment by domenic** [comment] 2022-05-09 04:59
Dupe of #2475

**Closed by domenic** 2022-05-09 04:59 UTC
