### ISSUE TITLE
Jsdom includes a dependency on the deprecated library request-promise-native

### ISSUE THREAD

**Issue by yarhamjohn** [jsdom/jsdom#3069] opened 2020-11-03 13:31 UTC
### Basic info:

`jsdom` has a dependency on `request-promise-native` which in turn has a peer-dependency on `request`. Both `request` and `request-promise-native` have been deprecated for some time now so I was wondering if there was a plan to migrate to a different library - some options were suggested here: https://github.com/request/request/issues/3143

**Comment by guimard** [comment] 2020-11-04 15:52
Hi,
looking at code, [axios](https://www.npmjs.com/package/axios) may be a code candidate:
 * provides native promise
 * has a "stream" mode that permits easily to fix [domexception/scripts/get-latest-platform-tests.js](domexception/scripts/get-latest-platform-tests.js)
 * there is a [axios-cookiejar-support](https://www.npmjs.com/package/axios-cookiejar-support) to fix [lib/jsdom/living/helpers/wrap-cookie-jar-for-request.js](lib/jsdom/living/helpers/wrap-cookie-jar-for-request.js)

**Comment by guimard** [comment] 2020-11-04 15:52
NB: duplicate of #3030

**Comment by guimard** [comment] 2020-11-04 15:55
See also #3031 and #3054

**Closed** 2021-03-07 19:22 UTC
