### ISSUE TITLE
Heap Memory Leakage

### ISSUE THREAD

**Issue by yashimversion** [jsdom/jsdom#2757] opened 2019-12-24 12:31 UTC
Hi,
I'm writing a server-side renderer for react application using JSDOM where it receives HTML as input and JSDOM executed javascript to build the page and spits out a rendered response (For many reasons we aren't using ReactDOMServer for server-side rendering). Although the page seems to render fine, the heap memory keeps increasing on every request until it crashes. I pretty much tried all the solutions listed in this Github issues related to memory leak i.e. usage of `window.close()` or custom collect garbage using `global.gc()`, but none of them seems to work. Also, I observed even if there are no requests for several hours, heap memory keeps increasing in small amounts until it crashed. Let me know how I can fix this. Thanks !!

### Basic info:

- **Node.js version: v10.16.3** 
- **jsdom version: 15.2.1** 

### Minimal reproduction case

```js
const resourceLoader = new jsdom.ResourceLoader( { strictSSL: false } );
const virtualConsole = new jsdom.VirtualConsole();

// Define JSDOM configurations.
const options = {
	contentType:    'text/html',
	referrer:       request.body.originUrl,
	resources:      resourceLoader,
	runScripts:     'dangerously',
	url:            ( request.body.originUrl + request.body.relativeUrl ),
	virtualConsole: virtualConsole.sendTo( console ),
	beforeParse( window ) {
		// Add event listener to know when page is fully loaded.
		window.addEventListener( 'load', function ( e ) {

		    const renderedHtml = dom.serialize(); // eslint-disable-line no-use-before-define

		    //Return response after page load.
		    response.send( renderedHtml );
	        } )
        },
};

// Render HTML and Javascript using JSDOM.
let dom = new JSDOM( request.body.html, options );
```

**Comment by Sebmaster** [comment] 2019-12-29 00:48
You'll need to get us a better repro, as-is this doesn't help us get to the bottom of the leaks unfortunately. Presumably if you turn off runScripts it'd work, indicating that some on-page scripts trigger a codepath that causes a leak.

**Comment by domenic** [comment] 2020-02-16 05:39
Closing since this does not contain enough information for us to reproduce. (However, fixes will be merged soon for a leak which may be related; we just have no way to tell from the code you've given.)

**Closed by domenic** 2020-02-16 05:39 UTC
Labels: memory
