### ISSUE TITLE
Blob.arrayBuffer is missing

### ISSUE THREAD

**Issue by markb-trustifi** [jsdom/jsdom#3592] opened 2023-09-06 12:10 UTC
### Basic info:

- **Node.js version:** 18.12.1
- **jsdom version:** 22.1.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM('<canvas></canvas>', {resources: "usable"});
let element = dom.window.document.getElementsByTagName('canvas');
element[0].toBlob(blob => {
    blob.arrayBuffer().then(buffer => {
        console.log(buffer.length);
    });
});
```

The `blob.arrayBuffer` doesn't exist and is not implemented here:
`/node_modules/jsdom/lib/jsdom/living/generated/Blob.js`

The code above is working with this workaround when I replace the JSDOM Blob with the Node.js native Blob:
`dom.window.Blob = Blob;`

**Comment by Shaun-Regenbaum** [comment] 2023-09-06 15:53
I am encountering the same thing.

**Comment by domenic** [comment] 2023-09-07 00:10
Dupe of https://github.com/jsdom/jsdom/issues/2555.

**Closed by domenic** 2023-09-07 00:10 UTC
