### ISSUE TITLE
can't delete window.onpagehide

### ISSUE THREAD

**Issue by asos-luissilva** [jsdom/jsdom#2140] opened 2018-02-01 14:35 UTC
### Basic info:

Since I migrated for the new version jsdom, looks like I can't delete window.onpagehide since is a property of his prototype.

- **Node.js version:** v8.9.4
- **jsdom version:** 11.6.2

### Minimal reproduction case

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const { window } = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);

console.log(Object.getOwnPropertyDescriptor(window, "onpagehide")); // undefined
console.log("before", window.onpagehide); // null
console.log(delete window.onpagehide); // true
console.log("after", window.onpagehide); // null
```

### How does similar code behave in browsers?

```js
// Mac 10.11.6 (15G1421)
// in Chrome Version 63.0.3239.84 (Official Build) (64-bit)

console.log(Object.getOwnPropertyDescriptor(window, "onpagehide")); // {get: ƒ, set: ƒ, enumerable: true, configurable: true}
console.log("before", window.onpagehide); // null
console.log(delete window.onpagehide); // true
console.log("after", window.onpagehide); // undefined
```

**Comment by domenic** [comment] 2018-02-01 16:42
You omitted the section of the issue template that asks you how similar code behaves in browsers. Please run such tests there first and then we can reopen the issue.

**Comment by asos-luissilva** [comment] 2018-02-02 10:22
Hi @domenic I omitted it, since in my case I'm using jsdom, for testing purposes (jest). And for the test I'm doing I need, I need to be able to delete it so I can test, when a browser has onpagehide and when it doesn't has it.

But I updated the issue to include, how it behaves in browser

**Comment by domenic** [comment] 2018-02-02 15:06
Thanks for updating! In general we're not interested in supporting testing use cases that can't be run as tests in the browser, so it's good you did.

My best guess at this point is this is a Node.js bug with their vm module :(. It might be worth trying v9.5.0, although I don't remember there being any fixes to vm on the 9.x branch. Sigh. So the action for us jsdom folks is to create a minimal test case (not involving jsdom, just Node.js's vm module), check if it's still broken on v9.5.0, check open issues on Node.js to see if it's already reported, and if not, report it to Node.js. I'm afraid there's no easy workaround for your case :(

**Comment by asos-luissilva** [comment] 2018-02-02 16:34
I tested in Node.js v9.5.0 but it still doesn't.

I don't think is a problem with the Node but the current implementation of the jsdom window.

in node:
```javascript
// in jsdom
console.log(Object.getOwnPropertyDescriptor(window, "onpagehide")); // undefined
console.log(window.hasOwnProperty("onpagehide")); // true
console.log(window.onpagehide); // null
```

in the browser:
```javascript
// Mac 10.11.6 (15G1421)
// in Chrome Version 63.0.3239.84 (Official Build) (64-bit)
console.log(Object.getOwnPropertyDescriptor(window, "onpagehide")); // {get: ƒ, set: ƒ, enumerable: true, configurable: true}
console.log(window.hasOwnProperty("onpagehide")); // true
console.log(window.onpagehide); // null
```

that means that the property "onpagehide" (in jsdom) doesn't belong to the object window but his prototype chain, and since it belongs to his prototype delete will not work.

> If a property with the same name exists on the object's prototype chain, then, after deletion, the object will use the property from the prototype chain (in other words, delete only has an effect on own properties).
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete

**Comment by domenic** [comment] 2018-02-02 18:01
Right, the issue is that we create our window object using Node.js's `vm` module, which does unfortunate and wonky things to the objects you feed it. We've had similar bugs in the past, and a number of them were fixed in Node v8, but it looks like there is still this one.

https://github.com/nodejs/node/issues/6287 seems related, but it looks like https://github.com/nodejs/node/pull/11266 landed sometime during the Node v7 cycle, so that fix probably wasn't sufficient :(.

**Comment by asos-luissilva** [comment] 2018-02-02 20:37
Yes it looks similar, and I tried to test the code examples in those issues and looks like those issues are really fixed in Node, or I don't know how to create that issue with `vm`.

But after trying to look how is implemented the eventHandlers in jsdom, I found the problem:

in [Window.js](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/Window.js#L610), if we move this line
```javascript
mixin(Window.prototype, WindowEventHandlersImpl.prototype);
```
and we apply it inside the function [Window](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/Window.js#L63)

```javascript
const window = this;
mixin(window, WindowEventHandlersImpl.prototype);
```

and if you run the minimal reproduction case in this issue, it will work.

I think is related to this comment that is in the [Window.js file](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/Window.js#L51)

> NOTE: per https://heycam.github.io/webidl/#Global, all properties on the Window object must be own-properties.
That is why we assign everything inside of the constructor, instead of using a shared prototype.
You can verify this in e.g. Firefox or Internet Explorer, which do a good job with Web IDL compliance.

**Comment by TimothyGu** [comment] 2018-02-02 20:41
That sounds like the right fix. Would you mind submitting a pull request and include some tests as well?

**Comment by asos-luissilva** [comment] 2018-02-02 20:43
Yes, I don't mind creating a PR and include some tests. Where should I create the tests?

**Comment by TimothyGu** [comment] 2018-02-02 20:45
Check out https://github.com/jsdom/jsdom/blob/master/Contributing.md.

**Comment by asos-luissilva** [comment] 2018-02-02 20:49
Thanks, I will try to create with my personal github account @fetz.

By the way, thanks @domenic and @TimothyGu for your great work

**Closed** 2018-02-05 16:34 UTC

**Comment by domenic** [comment] 2018-02-05 16:35
Thanks very much @asos-luissilva / @Fetz for your persistence with this bug report. Digging through past a mis-diagnosis by the maintainer, and then submitting a PR to fix the issue, is really great stuff. We'll get out a release with this soon.
