### ISSUE TITLE
Error: Not implemented: HTMLMediaElement.prototype.load

### ISSUE THREAD

**Issue by Rajdeepc** [jsdom/jsdom#3405] opened 2022-07-25 12:32 UTC
@domenic 
### Basic info:

- **Node.js version:** 14 and aboce
- **jsdom version:** v20

Environement: NodeJS

### Minimal reproduction case
```
             const videoElement = getVideoElement(url, options);
            console.log(videoElement);
            const source = videoElement.querySelector('source');
            if (options.fileType && videoElement.canPlayType(options.fileType) === "") {
                console.log("Cant play this video");
            }
            const object = new (cls || Media)(videoElement, options);
            object.set("url", url);
            object.set("__options", options);
            videoElement.loop = true;
            const onSeeked = () => {
                videoElement.pause();
                // middle frame loaded and we can play
                // now we can return ready video
                callback && callback(object);
                resolve(object);
                videoElement.removeEventListener("canplay", onSeeked);
            };
            const onLoad = () => {
                // Wait for video to load
                videoElement.addEventListener("canplay", onSeeked);
                // Seek middle frame - for sake of paused preview
                // we will get result after another canplay event
                videoElement.currentTime = videoElement.duration * 0.5;
                videoElement.width = videoElement.videoWidth;
                videoElement.height = videoElement.videoHeight;
                videoElement.removeEventListener("canplay", onLoad);
                videoElement.load();
                videoElement.play();
            };
            videoElement.addEventListener("canplay", onLoad);
            videoElement.addEventListener('error', (e) => {
                callback && callback(null, true);
                reject(e);
            });
            source.addEventListener('error', (e) => {
                callback && callback(null, true);
                reject(e);
            });
            videoElement.load(); ------- error points here
```
```
function getVideoElement(url, options) {
    const { document } = (new JSDOM()).window;
    console.log(document);
    let videoE = document.createElement('video');
    videoE.width = options.width;
    videoE.height = options.height;
    videoE.muted = true;
    videoE.playsInline = true;
    videoE.crossOrigin = "anonymous";
    // videoE.src = url
    let source = document.createElement('source');
    source.src = url;
    source.type = options.fileType || 'video/mp4';
    videoE.appendChild(source);
    // document.body.appendChild(videoE)
    return videoE;
}
/*
```

Getting the error 

<img width="1163" alt="Screenshot 2022-07-25 at 6 01 13 PM" src="https://user-images.githubusercontent.com/8790510/180777861-360a1cfd-1cf8-4776-8380-4426759718de.png">

**Comment by domenic** [comment] 2022-07-26 05:25
Dupe of https://github.com/jsdom/jsdom/issues/3405.

**Closed by domenic** 2022-07-26 05:25 UTC
