### ISSUE TITLE
[bug] fe164b3 broke Node 10.0 support.

### ISSUE THREAD

**Issue by MichaelDeBoey** [jsdom/jsdom#2941] opened 2020-04-11 13:48 UTC
### Basic info:

- **Node.js version:** 10.0.0
- **jsdom version:** 16.2.2

fe164b3 updated `webidl-conversions`' dependency to `6.x`, which requires `>= 10.4` (see https://github.com/jsdom/webidl-conversions/releases/tag/v6.0.0).
This was a breaking change for people using a lower Node `10` version.

This was discovered in https://github.com/testing-library/dom-testing-library/issues/521, which I further explored in https://github.com/testing-library/dom-testing-library/pull/525#issuecomment-612422897.

I also created #2940 to check this out in this repo

**Comment by TimothyGu** [comment] 2020-04-11 15:20
Let’s call this a duplicate of #2939.

I’m inclined to say that it’s your own responsibility to use the latest branch release, especially for LTS branches. Considering jsdom often uncover bugs in Node.js that get fixed in a bugfix release, I don’t know if we can ever “support” an ancient pre-LTS LTS branch release – especially not a *.0.0 release 2 years after its release. It is unfortunate that the changes slipped by without a major bump though.

I see that dom-testing-library only recently started allowing 10.0.0 in https://github.com/testing-library/dom-testing-library/issues/479. That’s quite unfortunate, though I’d point out that the original reporter was asking for 10.17.0 compatibility, which is in the range of versions that work well with jsdom.

**Closed by TimothyGu** 2020-04-11 15:20 UTC
