### ISSUE TITLE
queryselector within svg elements doesn't work (eg: document.querySelectorAll("svg.test") )

### ISSUE THREAD

**Issue by enotha** [jsdom/jsdom#2114] opened 2018-01-18 13:34 UTC
queryselector doesn't work with the combination of svg elements and classname. eg: "rect.test"
- **Node.js version: 8.9.4
- **jsdom version: 11.5.1
var html ='<!DOCTYPE html>\n'+
                    '<html>\n'+
                    '   <head>\n'+
                    '   </head>\n'+
                    '   <body> \n'+
 '   <div class=\'test'\> \n'+
                    '   </div>\n'+
 '   <svg class=\'test'\> \n'+
                    '   </svg>\n'+
                    '   </body>\n'+
                    '</html>';

_const { JSDOM } = require("jsdom");
const dom = new JSDOM(html);

// works.
console.log(dom.window.document.querySelectorAll("div.test"));
// doesn't work
console.log( dom.window.document.querySelectorAll("svg.test") );

**Comment by domenic** [comment] 2018-01-18 14:59
Basically a dupe of #2028, but technically a different test case, so let's leave this open, and try to fix both and include test cases for both.

**Comment by ekashida** [comment] 2019-11-08 23:43
I'm seeing the following behavior for `jsdom@15.2.1` where I'm not able to query the svg using a class selector:
```html
<foo-bar>
  #shadow
    <svg focusable="false" class="slds-icon-text-warning">...</svg>
</foo-bar>
```
```js
fooBar.shadowRoot.querySelector('svg')
=> SVGSVGElement
fooBar.shadowRoot.querySelector('[focusable]')
=> SVGSVGElement
fooBar.shadowRoot.querySelector('.slds-icon-text-warning')
=> null
```
However, it works fine if I wrap it with an element like this:
```html
<foo-bar>
  #shadow
    <div>
      <svg focusable="false" class="slds-icon-text-warning">...</svg>
    </div>
</foo-bar>
```
Please let me know if I should open a new issue for this.

**Closed** 2023-05-01 12:45 UTC
Labels: maybe fixed (add tests to confirm), selectors, svg
