### ISSUE TITLE
11.12.0 jsdom not working with jest + typescript

### ISSUE THREAD

**Issue by rszwabo** [jsdom/jsdom#2307] opened 2018-07-27 09:32 UTC
### Basic info:
The problem is that the latest jsdom which is required by jest and ts-jest does not work properly when starting the test. The issue seems to be related to the 11.12.0 version as everything works fine in jsdom v11.11.0 with the same configuration.

- **Node.js version:** v10.4.1
- **jsdom version:** 11.12.0 (latest)

### Minimal reproduction case
Run **npm install --save-dev jest ts-jest @types/jest typescript** as pointed in: https://www.npmjs.com/package/ts-jest

Create a tsconfig.json file containing:
```{
  "compilerOptions": {
    "sourceMap": true
  }
}
```

Create jest.config.js file containing:
```
module.exports = {
  transform: {
    "^.+\\.ts$": "ts-jest"
  },
  testRegex: "(/__tests__/.*|\\.test)\\.ts$",
  moduleFileExtensions: ["ts", "js", "json", "node"]
}
```

Run the test using jest, and this error will show up (from Window.js file, included in jsdom):
"SecurityError: localStorage is not available for opaque origins JEST test runner"

**Comment by Zirro** [comment] 2018-07-27 09:38
This is a duplicate of https://github.com/jsdom/jsdom/issues/2304.

**Closed by Zirro** 2018-07-27 09:38 UTC
