### ISSUE TITLE
Request module has been deprecated

### ISSUE THREAD

**Issue by vajahath** [jsdom/jsdom#2929] opened 2020-03-29 16:08 UTC
### Basic info:

- **Node.js version:** 13.11

### Minimal reproduction case

Request module is deprecated and showing warnings while installing. We are still using it ([example](https://github.com/jsdom/jsdom/blob/ffb4e0cad397db42b93d10794258bfd2053154ba/lib/jsdom/living/xhr/xhr-utils.js#L3)).

It would be nice if we could update this to got or something else.

(Noticed this when I was installing Jest)

```bash
$ npm install                           
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
...
...

$ npm ls request
@vaju/wishicat-general@1.0.0 /home/qbuser/gith/wishicat-general
└─┬ jest@25.2.3
  └─┬ @jest/core@25.2.3
    └─┬ jest-config@25.2.3
      └─┬ jest-environment-jsdom@25.2.3
        └─┬ jsdom@15.2.1
          └── request@2.88.2 
```

**Comment by TimothyGu** [comment] 2020-03-29 16:19
Duplicate of #2792.

**Closed by TimothyGu** 2020-03-29 16:19 UTC
