### ISSUE TITLE
document.body.innerText is undefined ?

### ISSUE THREAD

**Issue by masx200** [jsdom/jsdom#3226] opened 2021-08-06 03:29 UTC
### Basic info:

- **Node.js version:** v16.4.2
- **jsdom version:** ^16.7.0 

### Minimal reproduction case

```js
 const {JSDOM }=require('jsdom')
const document = new JSDOM("").window.document;
document.body.innerHTML='ssssssssss'
console.log( document.body.innerText)
//undefined
```

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)
```js
 const body = document.implementation.createHTMLDocument("").body;
body.innerHTML = 'sssssssssss'
console.log( body.innerText)
//sssssssssss
```

**Comment by domenic** [comment] 2021-08-06 03:39
Dupe of https://github.com/jsdom/jsdom/issues/1245

**Closed by domenic** 2021-08-06 03:39 UTC

**Comment by masx200** [comment] 2021-08-06 03:46
```js
 if ("undefined" === typeof body.innerText) {
        Object.defineProperty(body, "innerText", {
            get() {
                return this.textContent;
            },
            set(value) {
                this.textContent = value;
            },
        });
    }
```
