### ISSUE TITLE
Feature request: expanded set of reconfigurable window properties

### ISSUE THREAD

**Issue by rraziel** [jsdom/jsdom#2348] opened 2018-08-24 18:27 UTC
This is mostly for use with jest but I expect it could be useful for other scenarios.

It is about `reconfigure()`, which can be used to set `windowTop` and `url`, but nothing else.

It used to be possible (again, in jest) to simply do:
```javascript
Object.defineProperty(window, 'xx', {
    value: someValue
});
```
But that is no longer the case.

Having some mechanism that can override more properties of the `window` object would be really nice (and the absolute best: being able to define a getter rather than a simple value).
Maybe the ability to define some kind of delegate?

**Comment by domenic** [comment] 2018-08-24 18:29
This should still be possible. Only top is marked nonconfigurable.

Let me close this until you can edit it to use the issue template, which makes it clearer if this is an issue with jsdom vs. other stuff you are running, and what versions you are using.

**Closed by domenic** 2018-08-24 18:29 UTC

**Comment by rraziel** [comment] 2018-08-24 18:55
Sorry, I thought it was expected not to work and didn't think about reporting it as a bug.
I modified the description, but it's likely related to the way jest uses jsdom.

**Comment by domenic** [comment] 2018-08-24 19:04
Right, so this looks to me like it's working as intended, at least ignoring the jest stuff which is out of scope of this repo.

**Comment by rraziel** [comment] 2018-08-24 19:19
Alright, I'll see with jest directly, thanks.
