### ISSUE TITLE
The Range interface is missing getBoundingClientRect method

### ISSUE THREAD

**Issue by ctomczyk** [jsdom/jsdom#3178] opened 2021-04-18 16:12 UTC
### Basic info:

NodeJS v15.14.0
JSDom v16.5.3
OS: macOS 11.2.3

### Minimal reproduction case

[TypeScript]

    const selection: Selection | null = document.getSelection();
    const range: Range = selection.getRangeAt(0);
    const rect: DOMRect = range.getBoundingClientRect();

### Additional info

The `Range` interface is missing `getBoundingClientRect` method (at least; that's what I needed). The current wrapper returns:

    collapsed: (...)
    commonAncestorContainer: (...)
    endContainer: (...)
    endOffset: (...)
    startContainer: (...)
    startOffset: (...)

A full list of properties:

    /** A fragment of a document that can contain nodes and parts of text nodes. */
    interface Range extends AbstractRange {
        /**
         * Returns the node, furthest away from the document, that is an ancestor of both range's start node and end node.
         */
        readonly commonAncestorContainer: Node;
        cloneContents(): DocumentFragment;
        cloneRange(): Range;
        collapse(toStart?: boolean): void;
        compareBoundaryPoints(how: number, sourceRange: Range): number;
        /**
         * Returns −1 if the point is before the range, 0 if the point is in the range, and 1 if the point is after the range.
         */
        comparePoint(node: Node, offset: number): number;
        createContextualFragment(fragment: string): DocumentFragment;
        deleteContents(): void;
        detach(): void;
        extractContents(): DocumentFragment;
        getBoundingClientRect(): DOMRect;
        getClientRects(): DOMRectList;
        insertNode(node: Node): void;
        /**
         * Returns whether range intersects node.
         */
        intersectsNode(node: Node): boolean;
        isPointInRange(node: Node, offset: number): boolean;
        selectNode(node: Node): void;
        selectNodeContents(node: Node): void;
        setEnd(node: Node, offset: number): void;
        setEndAfter(node: Node): void;
        setEndBefore(node: Node): void;
        setStart(node: Node, offset: number): void;
        setStartAfter(node: Node): void;
        setStartBefore(node: Node): void;
        surroundContents(newParent: Node): void;
        toString(): string;
        readonly END_TO_END: number;
        readonly END_TO_START: number;
        readonly START_TO_END: number;
        readonly START_TO_START: number;
    }

**Comment by TimothyGu** [comment] 2021-08-06 04:25
Duplicate of #3002.

**Closed by TimothyGu** 2021-08-06 04:25 UTC
Labels: layout
