### ISSUE TITLE
cookieJar not used in XMLHttpRequest

### ISSUE THREAD

**Issue by matthieusieben** [jsdom/jsdom#1608] opened 2016-09-21 07:52 UTC
When performing AJAX requests, the cookieJar associated with the window should be used even on CORS domains.

**Comment by matthieusieben** [comment] 2016-09-21 08:08
All you need to set the cookies in the request is to add the following line in the `send(body)` method in `xmlhttprequest.js`:
```js
flag.requestHeaders.Cookie = flag.cookieJar.getCookieStringSync(flag.uri);
```

**Comment by joewalker** [comment] 2017-03-13 12:49
It looks like jsdom uses [xmlhttprequest](https://www.npmjs.com/package/xmlhttprequest) which says "*Known Issues / Missing Features: ... Cookies aren't persisted between requests*".

It looks from https://github.com/driverdan/node-XMLHttpRequest/blob/master/lib/XMLHttpRequest.js that it just doesn't support cookies at all.

Maybe the solution is for JSDom to take inspiration from [xmlhttprequest-cookie](https://www.npmjs.com/package/xmlhttprequest-cookie), except that it should use JSDom's cookieJar?

**Comment by domenic** [comment] 2017-03-13 16:17
> It looks like jsdom uses xmlhttprequest which says "Known Issues / Missing Features: ... Cookies aren't persisted between requests".

We do? I've never seen such code.

**Comment by joewalker** [comment] 2017-03-13 17:39
Ah, no, sorry. socket.io-client -> engine.io-client -> xmlhttprequest.
I assumed it was using the XHR from jsdom.

**Comment by roymiloh** [comment] 2018-04-02 15:53
Ok, so that's the issue - `request` [takes the cookies](https://github.com/request/request/blob/bbb3a0bbbe173342de8462a2171765a39681b248/request.js#L1456) from the url which the request is targeted to. However, with `withCredentials`, you want the cookies to be set up under `document.URL` url, for instance:

```js
cookieJar.setCookieSync('hello=world', document.URL);
```

So in order to solve it, you'd like to see something like this in `request`:

```js
cookies = targetCookieJar.getCookieString(document.URL)
```

Obviously it's not possible (and you don't want it anyway), so my suggestion is to do a small trick (based on [existing code](https://github.com/jsdom/jsdom/blob/d5639655d32d45b6690c9ac30901136e650eb99a/lib/jsdom/living/xhr-utils.js#L289-L291)):

```js
if (flag.cookieJar && (!crossOrigin || flag.withCredentials)) {
  if (flag.withCredentials) {
    // move cookies that belong to `document.URL` url to target url
  }

  options.jar = wrapCookieJarForRequest(flag.cookieJar);
}
```

Yes - it has a side effect on `CookieJar` instance, but we can duplicate it or smth so it won't affect the original one. Maybe there are some other things that I've not thought on (honestly, I took a glimpse into the spec, not a real deep dive).

@domenic wdyt? I can make a PR once we decide the way to go.

**Comment by domenic** [comment] 2018-04-02 16:03
Can you explain why you'd want the cookies to be set up under document.URL? Perhaps with an example? In particular, the original post in this thread does not have a test case I can understand.

**Comment by roymiloh** [comment] 2018-04-02 16:10
I'll add a test case later on, but I'll try to describe the scenario in a brief - I'm in a frame which its url is `A`. Now I want to make a cross origin request to `B`, so I added `withCredentials=true` to my `XMLHttpRequest` instance. What I'd expect is that my cookies (that are defined under `A`, which is my current `document.URL`) will be sent to `B` (because I marked the request with `withCredentials`, right?), and it doesn't happen, because what I've just describe above.

**Comment by domenic** [comment] 2018-04-02 16:42
I don't think that's how browsers work. You only send cookies for the target URL. But, I look forward to your test case (and especially running it in browsers).

**Comment by roymiloh** [comment] 2018-04-02 19:32
Ok, you're absolutely right. No reason to send frame's cookies to remote url. So I think I just got confused. Btw, I do get the cookies when I use cross origin request with `withCredentials`, so maybe it's worth to close this issue.

**Comment by domenic** [comment] 2018-04-23 02:52
Given the lack of reproducible test case, let me close this for now at least.

**Closed by domenic** 2018-04-23 02:52 UTC
Labels: important or easy
