### ISSUE TITLE
Support for node-canvas 2.x

### ISSUE THREAD

**Issue by tribetiki** [jsdom/jsdom#2135] opened 2018-01-30 14:05 UTC
Please add support for node-canvas 2.x versions:
https://github.com/Automattic/node-canvas
https://github.com/node-gfx/node-canvas-prebuilt

**Comment by domenic** [comment] 2018-01-30 15:31
Dupe of https://github.com/jsdom/jsdom/pull/1964

**Closed by domenic** 2018-01-30 15:31 UTC

**Comment by tribetiki** [comment] 2018-01-30 18:09
I did a search for "canvas" from open issues - didn't realize to check pull requests. Cheers! 👍
