### ISSUE TITLE
Window.toString()

### ISSUE THREAD

**Issue by harvey222** [jsdom/jsdom#3228] opened 2021-08-09 08:10 UTC
lots of native function has no protection
example:
in chrome: 
    Window.toString() ==> "function Window() { [native code] }"
but in jsdom: 
    Window.toString() has no protection

when jsdom is used crawling ,it will be found cheating

**Comment by domenic** [comment] 2021-08-09 13:58
Dupe of #3074

**Closed by domenic** 2021-08-09 13:58 UTC
