### ISSUE TITLE
cytoscape.js integration with jsdom

### ISSUE THREAD

**Issue by shotlom** [jsdom/jsdom#1067] opened 2015-03-20 09:41 UTC
Hi, 

I'd like to use jsdom to render svg images from cytoscape.js.

I tried following the D3.js example, but I can't figure out if jsdom is preventing cytoscape.js from recoginizing the window. Can you provide any advice?

https://github.com/cytoscape/cytoscape.js/issues/873

**Comment by Zirro** [comment] 2018-05-05 21:27
Given the time that has passed since this question was asked, and the lack of a minimal reproduction case which we'd generally require today, I'm going to close this issue.

**Closed by Zirro** 2018-05-05 21:27 UTC
Labels: question
