### ISSUE TITLE
dispatching click event executes click handler for disabled elements

### ISSUE THREAD

**Issue by eps1lon** [jsdom/jsdom#2665] opened 2019-09-17 13:14 UTC
### Basic info:

- **Node.js version:** 10.16.3
- **jsdom version:**  15.1.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const { window } = new JSDOM(`
<!DOCTYPE html>
<html>
  <body><button disabled></button></body>
</html>
`);

const button = window.document.querySelector('button');
button.addEventListener('click', () => console.log('click'));

button.click();
button.dispatchEvent(new window.MouseEvent('click'))
```
https://runkit.com/eps1lon/5d80dae1e7cc46001351ca95

### How does similar code behave in browsers?

https://jsbin.com/kebukirute/edit?html,js,console

In the browser no click handler is called. In JSDOM the click handler is called on dispatchEvent but not click().

**Comment by domenic** [comment] 2019-10-14 05:33
jsdom matches the spec and Firefox here. Blink and WebKit do not match the spec.

The interop issue here is tracked in https://github.com/whatwg/html/issues/2368, which may eventually lead to either fixing Blink and WebKit, or updating the spec to match them and then changing Firefox and jsdom. Until that gets done though, jsdom is behaving as intended, so I'll close this.

**Closed by domenic** 2019-10-14 05:33 UTC
