### ISSUE TITLE
innerHTML and outterHTML case that differs from browser behavior

### ISSUE THREAD

**Issue by weibangtuo** [jsdom/jsdom#3754] opened 2024-07-30 06:38 UTC
### Basic info:

- **Node.js version:** 18.18.2
- **jsdom version:** 24.1.1

### [Minimal reproduction case](https://stackblitz.com/edit/stackblitz-starters-zwczb6?file=test.js)

```js
const assert = require('node:assert').strict;
const { JSDOM } = require('jsdom');

const dom = new JSDOM('');
const document = dom.window.document;

const div = document.createElement('div');

div.innerText = '<b>a</b>';

assert.equal(div.innerHTML, '&lt;b&gt;a&lt;/b&gt;');
assert.equal(div.outerHTML, '<div>&lt;b&gt;a&lt;/b&gt;</div>');
```

### How does similar code behave in browsers?

In a typical browser environment, this test case should pass. But it didn't.

Refs https://github.com/capricorn86/happy-dom/issues/1494

**Comment by domenic** [comment] 2024-07-30 06:48
Unfortunately we cannot debug issues involving third-party packages like vitest. Please create a file we can run using `node test.js` and we're happy to reopen this issue.

**Comment by weibangtuo** [comment] 2024-07-31 06:27
@domenic Updated

**Comment by domenic** [comment] 2024-07-31 07:11
Thanks! It appears this issue is a dupe of #1245.

**Closed by domenic** 2024-07-31 07:11 UTC

**Comment by weibangtuo** [comment] 2024-07-31 11:49
Thanks!  Using `document.createTextNode` or `textContent` instead of `innerText` works well. It's better to behave like a commonly browser.

The following code can be passed.
```js
const assert = require('node:assert').strict;
const { JSDOM } = require('jsdom');

const dom = new JSDOM('');
const document = dom.window.document;

const div = document.createElement('div');

div.append(document.createTextNode('<b>a</b>'))
assert.equal(div.innerHTML, '&lt;b&gt;a&lt;/b&gt;');
assert.equal(div.outerHTML, '<div>&lt;b&gt;a&lt;/b&gt;</div>');

const div2 = document.createElement('div');

div2.textContent = '<b>a</b>'
assert.equal(div2.innerHTML, '&lt;b&gt;a&lt;/b&gt;');
assert.equal(div2.outerHTML, '<div>&lt;b&gt;a&lt;/b&gt;</div>');
```
