### ISSUE TITLE
Why aren't ValidityState[tooLong|tooShort] supported?

### ISSUE THREAD

**Issue by brophdawg11** [jsdom/jsdom#2493] opened 2019-01-18 04:27 UTC
### Basic info:

- **Node.js version:** 8.11.3
- **jsdom version:** 13.1.0

### Minimal reproduction case
n/a

I don't have a specific example, rather a question about the source code.  Can someone elaborate on this code comment and why `tooLong` and `tooShort` can't be implemented?  

https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLInputElement-impl.js#L777

It doesn't appear that other string-input validations require user-interactions (i.e., `patternMismatch`).  It is quite frustrating to only be able to test portions of the `ValidityState` API using `jsdom`.

### How does similar code behave in browsers?
ValidityState is fully functional

**Comment by domenic** [comment] 2019-01-18 12:32
The comment pretty clearly explains why, I think.

Please provide a code example that works in the browser but not jsdom and we can consider this further. Until then, closing.

**Closed by domenic** 2019-01-18 12:32 UTC

**Comment by brophdawg11** [comment] 2019-01-18 14:10
I opened the issue because I don't understand the comment...

**Comment by domenic** [comment] 2019-01-18 14:38
I'm very sorry; I skimmed and missed that you had already read the comment. I didn't mean to be dismissive.

The comment means that tooLong and tooShort cannot be caused by JavaScript, only user interaction (i.e., an actual user clicking and typing things on the screen). Since jsdom is a JavaScript library with a JavaScript API, and not a true web browser that you can click on and type things in to, tooLong and tooShort cannot be triggered in jsdom.

It's possible the comment is incorrect; I haven't read or investigated these parts of the spec in detail. But if the comment were incorrect, then you'd be able to provide a piece of JavaScript that works in the browser but not in jsdom. Thus my request.

**Comment by brophdawg11** [comment] 2019-02-02 21:54
No worries - I'll admit I didn't dig too deep beyond the comment either.  The [second link](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-maxlength) in the code contains a link to the [dirty value attribute](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-dirty), which made it clearer to me.

For kicks, I pout together a codepen to confirm the comment is still accurate: https://codepen.io/brophdawg11/pen/aPgqVE
