### ISSUE TITLE
[DOMParser] Spec behavior for noscript tags

### ISSUE THREAD

**Issue by xtuc** [jsdom/jsdom#1802] opened 2017-04-06 08:59 UTC
You can find the spec for DOMParser [here](https://w3c.github.io/DOM-Parsing/#the-domparser-interface)

The following example produce an incorrect output using JSDOM.

```js
console.log(
    (new window.DOMParser())
        .parseFromString('<noscript><div>foo</div><img /></noscript>', 'text/html')
        .body
        .innerHTML
);
```

#### Chrome

```html
<div>foo</div><img>
```

#### JSDom

Nothing.

If this is related to JSDom script configuration, I think (based on DOMParser spec) it should override the config.

I'm happy to help with a PR.

Edit:

In the HEAD:

```js
console.log(
    (new window.DOMParser())
        .parseFromString('<noscript><div>foo</div><img /></noscript>', 'text/html')
        .head // <---
        .innerHTML
);
```

#### JSDom

```html
<noscript><div>foo</div><img /></noscript>
```

#### Chrome

```html
<noscript></noscript>
```

**Comment by inikulin** [comment] 2017-04-06 09:21
`DOMParser` requires `scripting flag` to be disabled. However, currently [parse5](https://github.com/inikulin/parse5) (HTML parser used internally by jsdom) always acts as if we are in interactive user agent. Therefore, we need to implement `scripting flag` and related tree construction insertion modes in parse5 first.

**Comment by domenic** [comment] 2017-04-06 09:24
Of course, I think we are still behind by a major parse5 release or two, so getting that upgraded might be a prerequisite :(

**Comment by inikulin** [comment] 2017-04-06 09:44
@domenic It shouldn't be hard to implement. I guess we'll be able to lend it in `v4`. I've created an issue on parse5 side: https://github.com/inikulin/parse5/issues/192

**Comment by xtuc** [comment] 2017-04-06 11:33
Thanks for the fast answer.

`DOMParser` says that scripts are marked as executable. `scripting flag` configuration shouldn't alter this behavior.

**Comment by inikulin** [comment] 2017-04-06 11:39
> DOMParser says that scripts are marked as executable. scripting flag configuration shouldn't alter this behavior.

It says completely opposite: 
> The scripting flag must be set to "disabled".
NOTE
script elements get marked unexecutable and the contents of noscript get parsed as markup.

**Comment by xtuc** [comment] 2017-04-06 11:56
Yes absolutely, sorry. That's what I wanted to write.

**Comment by inikulin** [comment] 2017-04-06 16:02
@domenic 
> Of course, I think we are still behind by a major parse5 release or two, so getting that upgraded might be a prerequisite :(

I don't see any issue in upgrading jsdom to the latest parse5 at the moment. Without taking advantage of new features like `document.write` and streaming it should be basically just an API function name change.

**Comment by Sebmaster** [comment] 2017-04-06 16:06
Yeah, I had a branch which did this once upon a time. The upgrade itself shouldn't be a big deal.

**Comment by domenic** [comment] 2020-01-25 23:27
This may have been fixed by #2794, but we did not add a test for this case specifically.

I think the easiest path here is to wait for https://github.com/web-platform-tests/wpt/pull/21041 to land and then do a web platform tests role. Then, if the new tests pass, we can close this issue. If they fail, we have a bit more work to do.

**Comment by regseb** [comment] 2020-04-27 19:40
Hi,

I found a difference between _jsdom_ and browsers. I think the problem is related to this issue (but I can create another issue if necessary).

```javascript
const jsdom = require("jsdom");
const DOMParser = new jsdom.JSDOM().window.DOMParser;

const html = "<html><body>" +
               "<noscript>Hello <strong>world</strong></noscript>" +
             "</body></html>";
const doc = new DOMParser().parseFromString(html, "text/html");
const noscript = doc.querySelector("noscript");
console.log(noscript.textContent);
```

Here is the result with this code:

- _Firefox_ / _Chromium_ : `Hello world`;
- _jsdom_ _16.2.2_ : `Hello <strong>world</strong>`.

**Comment by regseb** [comment] 2023-05-25 14:34
@xtuc @domenic I tested these three scripts and I have the same results in Chromium 113.0.5672.126, Firefox 113.0.2 and jsdom 22.0.0 (Node.js v18.16.0). I think this problem is fixed.

---

```JavaScript
import jsdom from "jsdom";
const DOMParser = new jsdom.JSDOM().window.DOMParser;

const html = "<html><body>" +
               "<noscript>Hello <strong>world</strong></noscript>" +
             "</body></html>";
const doc = new DOMParser().parseFromString(html, "text/html");
const noscript = doc.querySelector("noscript");
console.log(noscript.textContent);
```

```
Hello world
```

---

```JavaScript
import jsdom from "jsdom";
const DOMParser = new jsdom.JSDOM().window.DOMParser;

console.log(
    (new DOMParser())
        .parseFromString('<noscript><div>foo</div><img /></noscript>', 'text/html')
        .body
        .innerHTML
);
```

```
<div>foo</div><img>
```

---

```JavaScript
import jsdom from "jsdom";
const DOMParser = new jsdom.JSDOM().window.DOMParser;

console.log(
    (new DOMParser())
        .parseFromString('<noscript><div>foo</div><img /></noscript>', 'text/html')
        .head // <---
        .innerHTML
);
```

```
<noscript></noscript>
```

**Comment by domenic** [comment] 2023-05-27 05:40
Thanks! And indeed, the web platform tests were rolled; this is tested in `domparsing/DOMParser-parseFromString-html.html` which is run on CI.

**Closed by domenic** 2023-05-27 05:40 UTC
Labels: parsing, maybe fixed (add tests to confirm)
