### ISSUE TITLE
innerText of a HTMLTimeElement is undefined

### ISSUE THREAD

**Issue by ceving** [jsdom/jsdom#3319] opened 2022-01-15 15:19 UTC
### Basic info:

- **Node.js version:** 12.22.5
- **jsdom version:** 19.0.0

### Minimal reproduction case

```js
#! /usr/bin/env node

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const frag = JSDOM.fragment(`<time> 31.12.2021 24:00 </time>`);
const time = frag.querySelector ('time');

console.log (`time: '${time}'`);
console.log (`time.textContent: '${time.textContent}'`);
console.log (`time.innerText: '${time.innerText}'`);
```

### How does similar code behave in browsers?

https://jsbin.com/zibujuvoxo/edit?html,js,console,output

`innerText` is the same as `textContent` but trimmed.

**Comment by domenic** [comment] 2022-01-15 17:24
Dupe of #1245.

**Closed by domenic** 2022-01-15 17:24 UTC
