### ISSUE TITLE
TypeError: Cannot read property '_location' of null

### ISSUE THREAD

**Issue by legraphista** [jsdom/jsdom#2121] opened 2018-01-22 19:25 UTC
### Basic info:

- **Node.js version:** v8.9.1
- **jsdom version:** 11.6.0

### Minimal reproduction case

When there is a network request, if the window is closed after the message is sent but before the message is received, the code will continue to run and any window access will result in this kind of error: 
```js
(node:15703) TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (/Users/Stefan/Desktop/Work/html-render/node_modules/jsdom/lib/jsdom/browser/Window.js:188:79)
    at fetch.then.then (./script.js:2:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

In this example I polyfill fetch and make a request from an external script.
As soon as the window loads I close it. 

*main.js*
```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const window = (new JSDOM(`<html>
    <head></head>
    <body>
        <script src="./script.js"></script>
    </body>
</html>`, {
  runScripts: "dangerously",
  resources: 'usable',
})).window;

window.fetch = require('node-fetch');

window.onload = () => {
  window.close();
};
```
*script.js*
```js
fetch('https://api.ipify.org').then(x => x.text()).then((ip) => {
  window.location.href = ip;
});
```

### How does similar code behave in browsers?
Window closes and any network request is aborted.

Since fetch in this case is an external implementation and uses node's I/O callback, i'm not sure how that callback can be stopped.

**Comment by domenic** [comment] 2018-01-22 19:26
Note that this will fail to fetch ./script.js entirely, since you haven't given a base URL. So fetch is a red herring.

**Comment by legraphista** [comment] 2018-01-22 19:33
@domenic i was expecting that too, but for some reason, it fetches the script, runs it and the closes.
Here's the above example.
```bash
Stefans-MacBook:html-render Stefan$ node --trace-warnings main.js 
(node:16639) TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (/Users/Stefan/Desktop/Work/html-render/node_modules/jsdom/lib/jsdom/browser/Window.js:188:79)
    at fetch.then.then (./script.js:2:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:16639) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at process._tickCallback (internal/process/next_tick.js:189:7)

```

**Comment by domenic** [comment] 2018-01-22 19:35
Hmm, OK.

Well, running code on the jsdom after closing it is not supported, so this is working as intended. I'd suggest modifying your script as follows:

```js
window.onload = () => {
  window.close();
  global.closedTheWindow = true;
};

// script.js
fetch('https://api.ipify.org').then(x => x.text()).then((ip) => {
  if (!global.closedTheWindow) {
    window.location.href = ip;
  }
});
```

**Comment by domenic** [comment] 2018-01-22 19:36
Wait, sorry, I forgot that `script.js` is running inside jsdom. Hmm, OK, so this is more our bug... although it's kind of tricky at the spec level too, whether promise callbacks run after window closing or not. Will work on it...

**Comment by legraphista** [comment] 2018-01-22 19:37
Also, using this polyfill https://github.com/github/fetch whick relies on `XMLHttpRequest` rather than node's I/O network implementation fixes the issue.

**Comment by domenic** [comment] 2018-01-22 19:38
Yeah, that makes sense, since we avoid sending XHR events after the window is closed.

**Comment by legraphista** [comment] 2018-01-22 19:46
Yup, looks like anything that has to do with node's I/O will trigger this, here's another example:

*main.js*
```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const { spawn } = require('child_process');

const window = (new JSDOM(`<html>
    <head></head>
    <body>
        <script src="./script.js"></script>
    </body>
</html>`, {
  runScripts: "dangerously",
  resources: 'usable',
})).window;

window.sleep = (cb) => {
  const p = spawn('sleep', [1]);
  p.on('close', cb);
};

window.onload = () => {
  window.close();
};
```

*script.js*
```js
sleep(() => window.location.href);
```

Results in: 
```bash
Stefans-MacBook:html-render Stefan$ node --trace-warnings main.js 
/Users/Stefan/Desktop/Work/html-render/node_modules/jsdom/lib/jsdom/browser/Window.js:188
      return idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._location);
                                                                              ^

TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (/Users/Stefan/Desktop/Work/html-render/node_modules/jsdom/lib/jsdom/browser/Window.js:188:79)
    at ChildProcess.sleep (./script.js:1:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

```

**Comment by legraphista** [comment] 2018-01-22 19:47
But since node's I/O is not part of the browser spec, I see how this issue might be irrelevant.

**Comment by TimothyGu** [comment] 2018-01-22 23:32
Not much we can do about this unfortunately, since V8 doesn't have an API for only running (or preventing from running) the microtasks corresponding to a particular context. Here's the relevant Node.js issue: https://github.com/nodejs/node/issues/3020.

What I would suggest is to use GitHub's Fetch polyfill. In general, passing things from the outside Node.js world into a browser breaks a lot of assumptions.

**Comment by frontendbeast** [comment] 2018-10-01 13:53
It's possible to stop the process exiting by adding a ternary around the location (and also history) getter function if `window._document` doesn't exist.  

```javascript
// Window.js 
// Lines 147 - 152

get location() {
  return (window._document) ? idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._location) : false;
},
get history() {
  return (window._document) ? idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._history) : false;
},
```

I don't know if that's the best way of doing it, but it does more gracefully handle calls to the window after it has been closed.

**Comment by merrywhether** [comment] 2021-09-27 15:58
For me, this arose from updating `jest-environment-jsdom` from 27.0.6 to 27.2.2, which both rely on `jsdom@^16.6.0`.

The issue in this case was a call to `self.close()` inside of some WebWorker code that was under test (and previously working). Replacing the spy with a full mock fixed the issue. This thread pointed me towards window lifecycle methods, but it seemed like Jest as fault here given the stable `jsdom` version.

**Comment by domenic** [comment] 2022-10-01 11:01
I think this was fixed in https://github.com/jsdom/jsdom/releases/tag/19.0.0.

**Closed by domenic** 2022-10-01 11:01 UTC

**Comment by daryllabar** [comment] 2023-06-01 12:13
Posting for anyone else that runs into this error.  For me, this was caused by a piece of code that I was testing that was calling window.close().  A simple `jest.spyOn(window, "close").mockImplementation(jest.fn());` in the test setup fixed the issue.
