### ISSUE TITLE
JSDOM spends a lot of time while parsing <script> tag content, even though JS is disabled

### ISSUE THREAD

**Issue by mrtcode** [jsdom/jsdom#2416] opened 2018-11-05 15:06 UTC
### Basic info:

- **Node.js version:** 8.10.0
- **jsdom version:** 13.0.0

### Minimal reproduction case:

[An example of an HTML file](https://gist.githubusercontent.com/mrtcode/29ce92eff745561c2baf12be9f629ef7/raw/539ea8e3a9724bd46146aad2304321bd9594b02b/example.html) that has only a `<script>` tag and takes more than half a minute to process it. It's enough to just run JSDOM without any options.
```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM(html);
```

The same is with `<style>` tags. I guess that JSDOM treats `<script>` and `<style>` tags just like regular tags and tries to parse HTML tags inside even though they are special tags and have JS or CSS.

More web pages that have this problem:
https://data.worldbank.org/indicator/EG.USE.COMM.FO.ZS?end=2015&start=1995&view=chart
https://www.newyorker.com/magazine/2011/10/31/foreign-campaigns
https://www.wsj.com/articles/SB10001424052970203471004577144672783559392
https://theintercept.com/

**Comment by Zirro** [comment] 2018-11-05 16:17
Thanks! This is likely the same issue as https://github.com/jsdom/jsdom/issues/2416, but we can keep this open until that's been verified.

I don't think the issue is that we're parsing the content of `<script>` and `<style>` as HTML, but rather that we're updating the `data` property of the text inside these elements far too frequently during parsing. It can probably be made a lot more efficient while still following the standard.

**Comment by domenic** [comment] 2018-12-02 23:05
Fixed by https://github.com/jsdom/jsdom/pull/2419, will do a new release soon!

**Closed by domenic** 2018-12-02 23:05 UTC
Labels: parsing, performance
